## 다중 로지스틱 회귀
- 변수 2개: 학습 시간, 과외 횟수

In [2]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [3]:
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

In [4]:
x_data = np.array([[2, 3], [4, 3], [6, 4], [8, 6], [10, 7], [12, 8], [14, 9]])
y_data = np.array([0, 0, 0, 1, 1, 1, 1]).reshape(7, 1)

In [6]:
x_data

array([[ 2,  3],
       [ 4,  3],
       [ 6,  4],
       [ 8,  6],
       [10,  7],
       [12,  8],
       [14,  9]])

In [7]:
y_data

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1]])

In [5]:
print(x_data.shape, y_data.shape)

(7, 2) (7, 1)


In [9]:
X = tf.placeholder(tf.float64, shape=[None, 2])
Y = tf.placeholder(tf.float64, shape=[None, 1])

In [12]:
w = tf.Variable(tf.random_uniform([2, 1], dtype = tf.float64))
b = tf.Variable(tf.random_uniform([1], dtype = tf.float64))

In [15]:

yhat = tf.sigmoid(tf.matmul(X, w) + b)

In [17]:
# binary-crossentropy: -y*log*yhat /// -(1-y)*log*(1-yhat)
loss = -tf.reduce_mean(Y + tf.log(yhat) + (1 - Y) * tf.log(1 - yhat))

In [18]:
learning_rate = 0.1

In [19]:
gradient_decent = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

In [20]:
# 0.5보다 크다면 1로 아니면 0으로 반환
predicted = tf.cast(yhat > 0.5, dtype=tf.float64)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.float64))

In [21]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for i in range(3001):
        w_, b_, loss_, _ = sess.run([w, b, loss, gradient_decent],
                                    feed_dict = {X: x_data, Y: y_data})
        if (i + 1) % 300 == 0:
            print("step = %d, w1=%.4f, w2=%.4f, b=%.4f, loss=%.4f"%
                 (i+1, w_[0], w_[1], b_, loss_))
    new_x = np.array([7, 6]).reshape(1, 2)
    new_y = sess.run(y, feed_dict={X:new_x})
    
    print("공부한 시간: %d, 과외 수업 횟수: %d" %(new_x[:,0], new_x[:, 1]))
    print("합격 가능성: %6.2f %%"%(new_y*100))

step = 300, w1=0.2003, w2=0.2074, b=-1.1122, loss=0.1034
step = 600, w1=0.0375, w2=0.6023, b=-1.8947, loss=0.0764
step = 900, w1=-0.0636, w2=0.8629, b=-2.4259, loss=0.0642
step = 1200, w1=-0.1292, w2=1.0418, b=-2.8024, loss=0.0582
step = 1500, w1=-0.1739, w2=1.1699, b=-3.0784, loss=0.0551
step = 1800, w1=-0.2057, w2=1.2647, b=-3.2860, loss=0.0533
step = 2100, w1=-0.2292, w2=1.3365, b=-3.4453, loss=0.0522
step = 2400, w1=-0.2469, w2=1.3919, b=-3.5694, loss=0.0516
step = 2700, w1=-0.2605, w2=1.4353, b=-3.6672, loss=0.0512
step = 3000, w1=-0.2712, w2=1.4696, b=-3.7451, loss=0.0510
공부한 시간: 7, 과외 수업 횟수: 6
합격 가능성:  95.99 %


### 계산으로 확인

In [22]:
m1 = np.array([7, 6]).reshape(1, 2)
m2 = np.array([0.1779, 1.5675]).reshape(2, 1)

In [23]:
np.matmul(m1, m2)

array([[10.6503]])

In [24]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [25]:
print(sigmoid(10,6503))

TypeError: sigmoid() takes 1 positional argument but 2 were given