In [21]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [22]:
seed = 2020
np.random.seed(seed)
tf.set_random_seed(seed)

In [32]:
x_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_data = np.array([0, 1, 1, 0])
y_data = y_data.reshape(4, 1)
print(x_data.shape, y_data.shape)
y_data

(4, 2) (4, 1)


array([[0],
       [1],
       [1],
       [0]])

In [33]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

In [34]:
W1 = tf.Variable(tf.random_normal([2, 2]), dtype = tf.float32)
b1 = tf.Variable(tf.random_normal([2]), dtype = tf.float32)
L1 = tf.sigmoid(tf.matmul(X, W1) + b1)

In [35]:
W2 = tf.Variable(tf.random_normal([2, 1]), dtype = tf.float32)
b2 = tf.Variable(tf.random_normal([1]), dtype = tf.float32)
hypo = tf.sigmoid(tf.matmul(L1, W2) + b2)

In [36]:
cost = -tf.reduce_mean(Y * tf.log(hypo) + (1.-Y) * tf.log(1.-hypo))

In [37]:
lr = 0.1
train = tf.train.AdamOptimizer(learning_rate=lr).minimize(cost)

In [38]:
predicted = tf.cast(hypo > 0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype = tf.float32))

In [39]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, cost_val)
    
    h, p, a = sess.run([hypo, predicted, accuracy], feed_dict={X:x_data, Y:y_data})
    print(f"\nHypothesis: \n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")
    
    W1_, b1_, W2_, b2_ = sess.run([W1, b1, W2, b2])
    print(f"\nW1:\n{W1_} \nb1:\n{b1_} \nW2:\n{W2_} \nb1:\n{b2_}")

0 0.80632377
1000 0.34705865
2000 0.3467155
3000 0.34663597
4000 0.3466055
5000 0.34659117
6000 0.34658378
7000 0.34658515
8000 0.34657812
9000 0.346577
10000 0.34657854

Hypothesis: 
[[1.2316697e-06]
 [9.9999130e-01]
 [4.9811244e-01]
 [4.9811268e-01]] 
Predicted:
[[0.]
 [1.]
 [0.]
 [0.]] 
Accuracy:
0.75

W1:
[[ 21.95029  -21.009443]
 [ -9.716    -11.652757]] 
b1:
[4.4015207 3.9182699] 
W2:
[[-11.720906]
 [-14.014651]] 
b1:
[11.713357]
