# LSTM을 이용한 텍스트 생성 / 개인

## 1. 데이터 전처리

In [1]:
import numpy as np
import pandas as pd
from string import punctuation

from tensorflow import keras
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical

Using TensorFlow backend.


In [2]:
df = pd.read_csv('data/ArticlesMay2017.csv')
df.head()

abstract                 articleID  articleWordCount  \
0      NaN  5906b3197c459f24986dd003              2412   
1      NaN  5906b3297c459f24986dd004              2318   
2      NaN  5906ceec7c459f24986dd021              1795   
3      NaN  5906cfa77c459f24986dd022               213   
4      NaN  5906e1c07c459f24986dd039              1342   

                   byline documentType  \
0          By IAN JOHNSON      article   
1  By EMMA G. FITZSIMMONS      article   
2           By MARC TRACY      article   
3        By SHANNON DOYNE      article   
4        By JASON STANLEY      article   

                                            headline  \
0                        My Beijing: The Sacred City   
1           6 Million Riders a Day, 1930s Technology   
2                  Seeking a Cross-Border Conference   
3  Questions for: ‘Despite the “Yuck Factor,” Lee...   
4                               Who Is a ‘Criminal’?   

                                            keywords  multimedia   newDesk  \
0  ['Travel and Vacations', 'Beijing (China)', 'R...           3    Travel   
1  ['Subways', 'Delays (Transportation)', 'Transi...          68     Metro   
2  ['Cetys University', 'College Athletics', 'Nat...           3    Sports   
3                                                 []           3  Learning   
4  ['Illegal Immigration', 'Traffic and Parking V...           3      OpEd   

   printPage              pubDate sectionName  \
0          1  2017-05-01 04:01:21     Unknown   
1          1  2017-05-01 04:01:33     Unknown   
2          1  2017-05-01 06:00:05     Unknown   
3          0  2017-05-01 06:03:03     Unknown   
4          0  2017-05-01 07:20:26     Unknown   

                                             snippet              source  \
0  This metropolis was once a total work of art, ...  The New York Times   
1  New York’s subway is struggling with old infra...  The New York Times   
2  Cetys University is making an ambitious bid to...  The New York Times   
3  How are leeches used to treat various medical ...  The New York Times   
4  Justice Roberts was right. The Trump administr...  The New York Times   

  typeOfMaterial                                             webURL  
0           News  https://www.nytimes.com/2017/05/01/travel/beij...  
1           News  https://www.nytimes.com/2017/05/01/nyregion/ne...  
2           News  https://www.nytimes.com/2017/05/01/sports/mexi...  
3           News  https://www.nytimes.com/2017/05/01/learning/qu...  
4          Op-Ed  https://www.nytimes.com/2017/05/01/opinion/who...

In [3]:
print(len(df.columns))
print(df.columns)

16
Index(['abstract', 'articleID', 'articleWordCount', 'byline', 'documentType',
       'headline', 'keywords', 'multimedia', 'newDesk', 'printPage', 'pubDate',
       'sectionName', 'snippet', 'source', 'typeOfMaterial', 'webURL'],
      dtype='object')


In [4]:
df['headline'].isnull().values.any()

False

In [5]:
headline = [head for head in df.headline.values]
headline[:5]

['My Beijing: The Sacred City',
 '6 Million Riders a Day, 1930s Technology',
 'Seeking a Cross-Border Conference',
 'Questions for: ‘Despite the “Yuck Factor,” Leeches Are Big in Russian Medicine’',
 'Who Is a ‘Criminal’?']

In [6]:
len(headline)

996

In [7]:
# 'Unknown'은 없었음. (차이 없음)
headline = [head for head in headline if head != 'Unknown']
len(headline)

935

In [8]:
def repreprocessing(s):
    s = s.encode('utf8').decode('ascii','ignore')
    return ''.join(c for c in s if c not in punctuation).lower()

In [9]:
text = [repreprocessing(x) for x in headline]
text[:5]

['my beijing the sacred city',
 '6 million riders a day 1930s technology',
 'seeking a crossborder conference',
 'questions for despite the yuck factor leeches are big in russian medicine',
 'who is a criminal']

In [10]:
# 단어 집합(vocabulary)을 만들고 크기를 확인
t = Tokenizer()
t.fit_on_texts(text)
vocab_size = len(t.word_index) + 1
print('단어 집합의 크기: %d' %vocab_size)

단어 집합의 크기: 2653


In [11]:
sequences = []
for line in text:
    encoded = t.texts_to_sequences([line])[0]
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
sequences[:11] # 11개의 샘플 출력

[[48, 799],
 [48, 799, 1],
 [48, 799, 1, 800],
 [48, 799, 1, 800, 57],
 [114, 406],
 [114, 406, 407],
 [114, 406, 407, 2],
 [114, 406, 407, 2, 179],
 [114, 406, 407, 2, 179, 801],
 [114, 406, 407, 2, 179, 801, 802],
 [803, 2]]

In [12]:
index_to_word = {}
for key, value in t.word_index.items():
    index_to_word[value] = key
print('빈도수 상위 1번 단어: ', index_to_word[1])
print('빈도수 상위 802번 단어: ', index_to_word[802])

빈도수 상위 1번 단어:  the
빈도수 상위 802번 단어:  technology


In [13]:
max_len = max(len(s) for s in sequences)
print('샘플의 최대 길이: ', max_len)

샘플의 최대 길이:  16


In [14]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0  48 799]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0  48 799   1]
 [  0   0   0   0   0   0   0   0   0   0   0   0  48 799   1 800]]


In [15]:
X = sequences[:,:-1]
y = sequences[:,-1]

In [16]:
# 레이블 데이터 y에 대해서 원-핫 인코딩을 수행
y = to_categorical(y, num_classes=vocab_size)

In [17]:
X.shape, y.shape

((5501, 15), (5501, 2653))

## 2. 모델 설계 및 학습

In [18]:
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Embedding, Dense, LSTM

In [19]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length=max_len-1, name = 'Embedding_Layer'))
model.add(LSTM(128, name = 'LSTM_Layer'))
model.add(Dense(vocab_size, activation='softmax', name = 'Output_Layer'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Embedding_Layer (Embedding)  (None, 15, 10)            26530     
_________________________________________________________________
LSTM_Layer (LSTM)            (None, 128)               71168     
_________________________________________________________________
Output_Layer (Dense)         (None, 2653)              342237    
Total params: 439,935
Trainable params: 439,935
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.compile(loss = 'categorical_crossentropy',
              optimizer = 'adam', metrics = ['accuracy'])

In [21]:
history = model.fit(X, y, epochs = 200, verbose = 1)

C:\Users\14\.conda\envs\tf2\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:433: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch 1/200
5501/5501 [==============================] - 2s 411us/step - loss: 7.4951 - accuracy: 0.0362
Epoch 2/200
5501/5501 [==============================] - 2s 363us/step - loss: 6.9891 - accuracy: 0.0351
Epoch 3/200
5501/5501 [==============================] - 2s 362us/step - loss: 6.8652 - accuracy: 0.0365
Epoch 4/200
5501/5501 [==============================] - 2s 377us/step - loss: 6.7665 - accuracy: 0.0429
Epoch 5/200
5501/5501 [==============================] - 2s 376us/step - loss: 6.6492 - accuracy: 0.0447
Epoch 6/200
5501/5501 [==============================] - 2s 366us/step - loss: 6.5026 - accuracy: 0.0484
Epoch 7/200
5501/5501 [==============================] - 2s 371us/step - loss: 6.3432 - accuracy: 0.0511
Epoch 8/200
5501/5501 [==============================] - 2s 349us/step - loss: 6.1735 - accuracy: 0.0551
Epoch 9/200
5501/5501 [==============================] - 2s 347us/step - loss: 5.9986 - accuracy: 0.0604
Epoch 10/200
5501/5501 [==============================]

5501/5501 [==============================] - 2s 367us/step - loss: 1.3603 - accuracy: 0.7171
Epoch 78/200
5501/5501 [==============================] - 2s 379us/step - loss: 1.3357 - accuracy: 0.7244
Epoch 79/200
5501/5501 [==============================] - 2s 340us/step - loss: 1.3085 - accuracy: 0.7335
Epoch 80/200
5501/5501 [==============================] - 2s 339us/step - loss: 1.2900 - accuracy: 0.7350
Epoch 81/200
5501/5501 [==============================] - 2s 342us/step - loss: 1.2643 - accuracy: 0.7402
Epoch 82/200
5501/5501 [==============================] - 2s 342us/step - loss: 1.2364 - accuracy: 0.7450
Epoch 83/200
5501/5501 [==============================] - 2s 342us/step - loss: 1.2141 - accuracy: 0.7520
Epoch 84/200
5501/5501 [==============================] - 2s 394us/step - loss: 1.1914 - accuracy: 0.7540
Epoch 85/200
5501/5501 [==============================] - 2s 377us/step - loss: 1.1688 - accuracy: 0.7610
Epoch 86/200
5501/5501 [==============================] - 2

5501/5501 [==============================] - 2s 386us/step - loss: 0.4179 - accuracy: 0.89240s
Epoch 154/200
5501/5501 [==============================] - 2s 394us/step - loss: 0.4152 - accuracy: 0.8924
Epoch 155/200
5501/5501 [==============================] - 2s 393us/step - loss: 0.4104 - accuracy: 0.8926
Epoch 156/200
5501/5501 [==============================] - 2s 368us/step - loss: 0.4055 - accuracy: 0.89350s - l
Epoch 157/200
5501/5501 [==============================] - 2s 396us/step - loss: 0.4034 - accuracy: 0.8924
Epoch 158/200
5501/5501 [==============================] - 2s 399us/step - loss: 0.4001 - accuracy: 0.8933
Epoch 159/200
5501/5501 [==============================] - 2s 346us/step - loss: 0.3977 - accuracy: 0.8962
Epoch 160/200
5501/5501 [==============================] - 2s 342us/step - loss: 0.3934 - accuracy: 0.8951
Epoch 161/200
5501/5501 [==============================] - 2s 340us/step - loss: 0.3907 - accuracy: 0.8926
Epoch 162/200
5501/5501 [==================

## 3. 모델 검증

In [22]:
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=15, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)
          # 입력한 X(현재 단어)에 대해서 y를 예측하고 y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장

    sentence = init_word + sentence
    return sentence

In [23]:
headline[10]

'What’s Going On in This Picture? | May 1, 2017'

In [24]:
print(sentence_generation(model, t, "What's", 5))

What's pop will the lone wolves
